name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install the latest stable Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt,clippy
          rustup default stable
      - name: Verify
        run: make verify
      - name: Build and test the container
        run: make build
